config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  
  resources :users
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    #books(投稿)に対してコメントをするからコメントのモデルを親子関係にする
  end

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :title, presence: true
    validates :body, {presence: true, length: {maximum:200} }
    
    
    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_many :books, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    #has_manyの後のモデル名は複数形

    has_one_attached :profile_image


  validates :name, {uniqueness: true, length: {in: 2..20}}
  validates :introduction, {length: {maximum:50} }



def get_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    before_action :authenticate_user!, except: [:top, :about]
    
    
    
    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end
    
    
    def after_sign_out_path_for(resource)
      root_path
    end
    
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        comment = BookComment.new(book_comment_params)
        comment.user_id = current_user.id
        comment.book_id = book.id 
        #comment.book_id(ログインユーザーの新規コメントのbook_id=createの1行目のbookのidと同じ)
        comment.save
        redirect_to book_path(book.id)
    end
    
    def destroy
        BookComment.find(params[:id]).destroy
        redirect_back fallback_location: books_path
    end
    
    
    
    private
    
    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :is_matching_login_book, only: [:destroy, :edit, :update]
  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def create
    @book = Book.new(book_params)
    @books = Book.all
    @user = current_user
    @book.user_id = current_user.id
     
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @books = Book.find(params[:id])
    @user = current_user
    @book = Book.new
    @book_comment = BookComment.new
  end
  
  def update
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
     @book = Book.find(params[:id])
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_book
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
    redirect_to books_path
  end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back fallback_location: book_path(book)
    end
    
    
    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back fallback_location: books_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
      @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
  
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
    redirect_to user_path(current_user.id)
  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
    <div class="row">
        <div class="mx-auto col-3">
          
          <% if @book.errors.any? %>
            <%= @book.errors.count %>errors prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          
          
          
          <h2>Editing Book</h2>
          
          <%= form_with model: @book do |f| %>
          
          <label>Title</label></br>
            <%= f.text_field :title %><br>
            
            <label>Opinion</label></br>
            <%= f.text_area :body %><br>
            
            <%= f.submit "Update Book", class: "btn btn-success" %></br>
            
            <%= link_to "Show", book_path(@book.id) %>
            <span>|</span>
            <%= link_to "Back", books_path %>
          <% end %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    
    <div class = "col-md-3">
      <%= render 'users/userinfo', user: @user, book: @book %>
    </div>
    
    
    <div class = "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
      
      <% @books.each do |books| %>
        <tr>
          <td><%= image_tag books.user.get_image(100,100) %><br><%= link_to books.user.name, user_path(books.user.id) %></td>
          
          <td><%= link_to books.title, book_path(books.id) %></td>
          <td><%= books.body %></td>
          
        <% if books.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(books), method: :delete do %>
            <i class="fas fa-heart"></i><%= books.favorites.count %>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to book_favorites_path(books), method: :post do %>
            <i class="fas fa-heart"></i><%= books.favorites.count %>
        <% end %>
          </td>
        <% end %>
          
          <td>コメント数：<%= books.book_comments.count %></td>
        </tr>
      <% end %>
      </table>
    </div>
    </div>
</diV>

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class="container">
    <div class="row">
      
    <div class = "col-md-3">
        <%= render 'users/userinfo', user: @books.user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    
    <table class= "table table-striped">
    <tr>
        <td><%= image_tag @books.user.get_image(100,100) %><br><%= link_to @books.user.name, user_path(@books.user_id) %></td>
        <td><%= link_to @books.title, book_path(@books.id) %></td> 
        <td><%= @books.body %></td>
        
        <% if @books.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@books.id), class: "btn btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %></td>
        <% end %>
          
        <% if @books.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(@books), method: :delete do %>
            <i class="fas fa-heart"></i><%= @books.favorites.count %>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to book_favorites_path(@books), method: :post do %>
            <i class="fas fa-heart"></i><%= @books.favorites.count %>
            <% end %>
          </td>
        <% end %>
          
          <td>コメント数：<%= @books.book_comments.count %></td>
    </tr>
    </table>
    
    <div>
      <% @books.book_comments.each do |book_comment| %>
      <table>
        <tr>
          <td><%= image_tag book_comment.user.get_image(100,100) %><br><%= link_to book_comment.user.name %></td>
          <td><%= book_comment.comment %></td>
          <td>
            <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %>
            <!--book_comment(@booksのbook_commentsを1つずついれたやつ),book_commentをとるには、どの投稿にコメントしたもの貸る必要があるため、book情報とbook_comment情報を取得している-->
            <% end %>
          </td>
        </tr>
      </table>
      <% end %>
    </div>
    <div>
      <%= form_with model: [@books, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: '3' %>
        <br>
        <%= f.submit "送信" %>
      <% end %>
    </div>
    
    </div>
    </div>
</div>

app/views/homes/about.html.erb
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
    <div class="row">
        <div class="mx-auto col-5">
            <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
        </div>
    </div>
</div>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/8c3165965e.js" crossorigin="anonymous"></script>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= flash[:notice] %>

<div class="container">
    <div class="row">
        <div class="mx-auto col-5">
        <h1>welcome to <i class="fas fa-book"></i><b>Bookers</b>!!</h1>

        <p>
            In <i class="fas fa-book"></i><b>Bookers</b>,<br>
            you can share and exchange your opinions, inpressions,<br>
            and emotions
        </p>
        
        <p>about various books!</p>
        
        <div class="btn-wrapper col-2 mx-auto">
            <div class="row">
                <%= link_to "Log in", new_user_session_path %>
                <!--<button class="btn-block btn btn-primary" type="button">Log in</button>-->
                <!--% end %-->
            </div>
            <div class="row">
                <%= link_to "Sign up", new_user_registration_path %>
                <!--button class="btn-block btn btn-success" type="button">Sign up</button-->
                <!--% end %-->
            </div>
            
        </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <script src="https://kit.fontawesome.com/8c3165965e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <h3>
            <a class="navbar-brand" href="/">Bookers</a>
          </h3>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          
      
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>
              <span>Home</span>
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i>
              <span>Users</span>
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i>
              <span>Books</span>
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i>
              <span>logout</span>
              <% end %>
            </li>
            
            <% else %>
            
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i>
              <span>Home</span>
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to home_about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i>
              <span>About</span>
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i>
              <span>sign up</span>
              <% end %>
            </li>
            
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i>
              <span>login</span>
              <% end %>
            </li>
            
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>
    
    <div class="row">
      <div class="mx-auto col-2">
        <footer>
          <p>CopyRight Infratop.inc</p>
        </footer>
      </div>
    </div>
    
  </body>
</html>

app/views/users/_userinfo.html.erb
      
      <script src="https://kit.fontawesome.com/8c3165965e.js" crossorigin="anonymous"></script>
      
      
      <h2>User info</h2>
      
      <table>
        <tr>
          <%= image_tag user.get_image(100,100) %>
        </tr>
        
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        
        <tr>
          <th>
            <%= link_to edit_user_path(user.id), class: "btn-block btn btn-outline-secondary" do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
          </th>
        </tr>
      </table>
      
      
      
      <h2>New book</h2>
      <%= form_with model: book do |f| %>
      
      <h4>Title</h4>
      <%= f.text_field :title %>
      
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      
      <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>

app/views/users/edit.html.erb
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container">
    <div class="row">
        <div class="mx-auto col-3">

          <% if @user.errors.any? %>
            <%= @user.errors.count %>errors prohibited this obj from being saved:
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          
          
          
          <h2>User info</h2>
          
          <%= form_with model: @user do |f| %>
            
            <label for="inputName">Name</label></br>
            <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
            
            <label for="inputImage">Image</label>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
            
            <label for="inputIntroduction">Introduction</label>
            <%= f.text_area :introduction %><br>
            
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    
    <div class="row">
        <div class = "col-md-3">
            <%= render 'userinfo', user: @user, book: @book %>
        </div>
    
    
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            
            <table class="table table-striped">
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th></th>
                </tr>
                
                <% @users.each do |users| %>
                <tr>
                    <td>
                        <%= image_tag users.get_image(100,100) %>
                    </td>
                    
                    <td><%= users.name %></td>
                    <td><%= link_to 'Show', user_path(users.id) %></td>
                </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container">
    <div class="row">
      
     <div class = "col-md-3">
        <%= render 'userinfo', user: @user, book: @book %>
    </div>
    
    
    <div class = "col-md-8 offset-md-1">
        
        <h2>Books</h2>
        <table class = "table table-striped">
            
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
                <th></th>
            </tr>
            
            <% @user.books.each do |books| %>
            <tr>
                <td>
                    <%= link_to user_path(@user.id) do %>
                    <%= image_tag @user.get_image(100,100) %>
                    <% end %>
                </td>
                
                <td><%= link_to books.title, book_path(books.id) %></td>
                <td><%= books.body %></td>
                
                
                <% if books.favorited_by?(current_user) %>
                  <td>
                    <%= link_to book_favorites_path(books), method: :delete do %>
                    <i class="fas fa-heart"></i><%= books.favorites.count %>
                    <% end %>
                  </td>
                <% else %>
                  <td>
                    <%= link_to book_favorites_path(books), method: :post do %>
                    <i class="fas fa-heart"></i><%= books.favorites.count %>
                    <% end %>
                  </td>
                <% end %>
                
                
                <td>コメント数：<%= books.book_comments.count %></td>
            </tr>
            <% end %>
        </table>
    </div>
    </div>
</div>